---

- name: Install PostgreSQL
  apt: name={{ item }}
       update_cache=no
       state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2
  tags: packages

- name: Ensure Postgresql is running
  service: name=postgresql
           state=started
           enabled=yes

- name: Create db
  become: yes
  become_user: postgres
  become_pass: vagrant
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present

- name: Ensure user has access to the database
  become: yes
  become_user: postgres
  become_pass: vagrant
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present

- name: Ensure user does not have unnecessary privileges
  become: yes
  become_user: postgres
  become_pass: vagrant
  postgresql_user: name={{ db_user }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present
