---

- name: Install base packages
  become_user: root
  apt: name={{ item }}
       update_cache=yes
       force=yes
       state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - libpq-dev
    - python-dev
    - python-pip
    - python-pycurl
    - supervisor
